"""Pure assembly of the existing trained-model bundle schemas."""

from __future__ import annotations

from typing import Any

from system_identification.models.features import resolve_window_feature_columns
from system_identification.training.losses import _target_loss_weights_as_dict

def assemble_sequence_training_bundle(
    *,
    amp_enabled,
    asl_dropout,
    asl_hidden_size,
    asl_max_frequency_bins,
    base_feature_columns,
    best_epoch,
    best_state_dict,
    best_val_loss,
    current_feature_columns,
    current_feature_means,
    current_feature_medians,
    current_feature_mode,
    current_feature_stds,
    dropout,
    film_hidden_size,
    film_mode,
    film_scale,
    gru_num_layers,
    hidden_sizes,
    history,
    huber_delta,
    lr_warmup_ratio,
    phase_conditioning_columns,
    phase_conditioning_indices,
    random_seed,
    resolved_device,
    resolved_ema_decay,
    resolved_gradient_clip_norm,
    resolved_loss_type,
    resolved_lr_scheduler,
    resolved_model_type,
    resolved_prior_loss_weight,
    resolved_prior_target_columns,
    sequence_feature_columns,
    sequence_feature_means,
    sequence_feature_medians,
    sequence_feature_mode,
    sequence_feature_stds,
    sequence_history_size,
    target_loss_weights_array,
    target_means,
    target_stds,
    tcn_channels,
    tcn_kernel_size,
    tcn_num_blocks,
    train_sequence_scaled,
    train_targets_df,
    transformer_d_model,
    transformer_dim_feedforward,
    transformer_num_heads,
    transformer_num_layers,
    transformer_use_positional_encoding,
    val_sequence_scaled,
    warmup_steps,
) -> dict[str, Any]:
    return {
        "model_state_dict": best_state_dict,
        "model_type": resolved_model_type,
        "feature_columns": list(base_feature_columns),
        "base_feature_columns": list(base_feature_columns),
        "target_columns": list(train_targets_df.columns),
        "sequence_feature_columns": list(sequence_feature_columns),
        "current_feature_columns": list(current_feature_columns),
        "sequence_feature_medians": sequence_feature_medians,
        "sequence_feature_means": sequence_feature_means,
        "sequence_feature_stds": sequence_feature_stds,
        "current_feature_medians": current_feature_medians,
        "current_feature_means": current_feature_means,
        "current_feature_stds": current_feature_stds,
        "target_means": target_means,
        "target_stds": target_stds,
        "target_loss_weights": target_loss_weights_array,
        "target_loss_weights_by_name": _target_loss_weights_as_dict(list(train_targets_df.columns), target_loss_weights_array),
        "prior_target_columns": resolved_prior_target_columns,
        "prior_loss_weight": float(resolved_prior_loss_weight),
        "loss_type": resolved_loss_type,
        "huber_delta": float(huber_delta),
        "sequence_history_size": int(sequence_history_size),
        "sequence_feature_mode": sequence_feature_mode,
        "current_feature_mode": current_feature_mode,
        "sequence_group_columns": ["log_id", "segment_id"],
        "sequence_sort_column": "time_s",
        "sequence_sample_count_train": int(len(train_sequence_scaled)),
        "sequence_sample_count_val": int(len(val_sequence_scaled)),
        "hidden_sizes": list(hidden_sizes),
        "dropout": float(dropout),
        "gru_hidden_size": int(hidden_sizes[0]),
        "gru_num_layers": int(gru_num_layers),
        "asl_hidden_size": int(asl_hidden_size),
        "asl_dropout": float(asl_dropout),
        "asl_max_frequency_bins": asl_max_frequency_bins,
        "tcn_channels": int(tcn_channels),
        "tcn_num_blocks": int(tcn_num_blocks),
        "tcn_kernel_size": int(tcn_kernel_size),
        "transformer_d_model": int(transformer_d_model),
        "transformer_num_layers": int(transformer_num_layers),
        "transformer_num_heads": int(transformer_num_heads),
        "transformer_dim_feedforward": int(transformer_dim_feedforward),
        "transformer_use_positional_encoding": bool(transformer_use_positional_encoding),
        "film_mode": film_mode,
        "phase_conditioning_columns": phase_conditioning_columns,
        "phase_conditioning_indices": list(phase_conditioning_indices or []),
        "film_hidden_size": int(film_hidden_size),
        "film_scale": float(film_scale),
        "lr_scheduler": resolved_lr_scheduler,
        "lr_warmup_ratio": float(lr_warmup_ratio),
        "lr_warmup_steps": int(warmup_steps),
        "gradient_clip_norm": resolved_gradient_clip_norm,
        "ema_decay": float(resolved_ema_decay),
        "best_epoch": int(best_epoch),
        "best_val_loss": float(best_val_loss),
        "history": history,
        "device_type": resolved_device.type,
        "use_amp": bool(amp_enabled),
        "random_seed": int(random_seed),
    }
def assemble_rollout_training_bundle(
    *,
    amp_enabled,
    base_feature_columns,
    best_epoch,
    best_state_dict,
    best_val_loss,
    context_feature_columns,
    context_feature_means,
    context_feature_medians,
    context_feature_stds,
    ct_integrator,
    current_feature_columns,
    current_feature_means,
    current_feature_medians,
    current_feature_mode,
    current_feature_stds,
    dropout,
    dt_over_tau,
    gru_num_layers,
    hidden_sizes,
    history,
    huber_delta,
    latent_size,
    random_seed,
    resolved_device,
    resolved_loss_type,
    resolved_model_type,
    resolved_rollout_stride,
    resolved_target_columns,
    rollout_feature_columns,
    rollout_feature_means,
    rollout_feature_medians,
    rollout_feature_stds,
    rollout_size,
    sequence_feature_mode,
    sequence_history_size,
    target_loss_weights_array,
    target_means,
    target_stds,
    train_context_scaled,
    train_targets,
    val_context_scaled,
    val_targets,
) -> dict[str, Any]:
    return {
        "model_state_dict": best_state_dict,
        "model_type": resolved_model_type,
        "feature_columns": list(base_feature_columns),
        "base_feature_columns": list(base_feature_columns),
        "target_columns": list(resolved_target_columns),
        "context_feature_columns": list(context_feature_columns),
        "rollout_feature_columns": list(rollout_feature_columns),
        "current_feature_columns": list(current_feature_columns),
        "context_feature_medians": context_feature_medians,
        "context_feature_means": context_feature_means,
        "context_feature_stds": context_feature_stds,
        "rollout_feature_medians": rollout_feature_medians,
        "rollout_feature_means": rollout_feature_means,
        "rollout_feature_stds": rollout_feature_stds,
        "current_feature_medians": current_feature_medians,
        "current_feature_means": current_feature_means,
        "current_feature_stds": current_feature_stds,
        "target_means": target_means,
        "target_stds": target_stds,
        "target_loss_weights": target_loss_weights_array,
        "target_loss_weights_by_name": _target_loss_weights_as_dict(list(resolved_target_columns), target_loss_weights_array),
        "loss_type": resolved_loss_type,
        "huber_delta": float(huber_delta),
        "sequence_history_size": int(sequence_history_size),
        "rollout_size": int(rollout_size),
        "rollout_stride": int(resolved_rollout_stride),
        "sequence_feature_mode": sequence_feature_mode,
        "current_feature_mode": current_feature_mode,
        "sequence_group_columns": ["log_id", "segment_id"],
        "sequence_sort_column": "time_s",
        "rollout_sample_count_train": int(len(train_context_scaled)),
        "rollout_timestep_count_train": int(train_targets.shape[0] * train_targets.shape[1]),
        "rollout_sample_count_val": int(len(val_context_scaled)),
        "rollout_timestep_count_val": int(val_targets.shape[0] * val_targets.shape[1]),
        "hidden_sizes": list(hidden_sizes),
        "dropout": float(dropout),
        "gru_hidden_size": int(hidden_sizes[0]),
        "gru_num_layers": int(gru_num_layers),
        "latent_size": int(latent_size),
        "dt_over_tau": float(dt_over_tau),
        "ct_integrator": ct_integrator,
        "best_epoch": int(best_epoch),
        "best_val_loss": float(best_val_loss),
        "history": history,
        "device_type": resolved_device.type,
        "use_amp": bool(amp_enabled),
        "random_seed": int(random_seed),
    }


def assemble_training_bundle(
    *,
    amp_enabled,
    base_feature_columns,
    best_epoch,
    best_state_dict,
    best_val_loss,
    dropout,
    feature_means,
    feature_medians,
    feature_stds,
    hidden_sizes,
    history,
    huber_delta,
    pfnn_control_points,
    pfnn_expanded_input_dim,
    pfnn_phase_node_count,
    phase_feature_index,
    random_seed,
    resolved_device,
    resolved_loss_type,
    resolved_model_type,
    resolved_window_mode,
    target_loss_weights_array,
    target_means,
    target_stds,
    train_features_df,
    train_targets_df,
    window_feature_mode,
    window_radius,
) -> dict[str, Any]:
    return {
        "model_state_dict": best_state_dict,
        "model_type": resolved_model_type,
        "feature_columns": list(train_features_df.columns),
        "base_feature_columns": list(base_feature_columns),
        "target_columns": list(train_targets_df.columns),
        "feature_medians": feature_medians,
        "feature_means": feature_means,
        "feature_stds": feature_stds,
        "target_means": target_means,
        "target_stds": target_stds,
        "target_loss_weights": target_loss_weights_array,
        "target_loss_weights_by_name": _target_loss_weights_as_dict(list(train_targets_df.columns), target_loss_weights_array),
        "loss_type": resolved_loss_type,
        "huber_delta": float(huber_delta),
        "window_mode": resolved_window_mode,
        "window_radius": int(window_radius),
        "window_feature_mode": window_feature_mode,
        "window_feature_columns": resolve_window_feature_columns(list(base_feature_columns), window_feature_mode),
        "hidden_sizes": list(hidden_sizes),
        "dropout": float(dropout),
        "phase_feature_index": phase_feature_index,
        "phase_feature_column": train_features_df.columns[phase_feature_index] if phase_feature_index is not None else None,
        "pfnn_expanded_input_dim": int(pfnn_expanded_input_dim),
        "pfnn_phase_node_count": int(pfnn_phase_node_count),
        "pfnn_control_points": int(pfnn_control_points),
        "best_epoch": int(best_epoch),
        "best_val_loss": float(best_val_loss),
        "history": history,
        "device_type": resolved_device.type,
        "use_amp": bool(amp_enabled),
        "random_seed": int(random_seed),
    }
